### PR TITLE
RepositoryProvider and ThemeProvider separated from ChatProvider

### PR DESCRIPTION
**Pull request by Chesteer89**
Does it make sense to separate it this way?

### CODE REVIEW

**Comment by CraigLn** [comment]
> Does it make sense to separate it this way?

I think if we stat moving away from the "Chat Provider" being the holder of all the things then it makes sense, but it depends on what you're trying to solve.  What was the driving force behind making this change?

**Comment by Chesteer89** [comment]
The initialization of repositories is done in `ChatProvider`. It means, that for logging purposes we're not able to get users directly from repository without PN initialization. We don't want to add workarounds like init with a dummy username, so extracting repository initialization code allows us to call it directly when other component parts are not needed.

**Review by mateusz-cichosz — APPROVED** [review]

**Comment by Chesteer89** [comment]
Docs PR: 
https://github.com/pubnub/documentation/pull/207

**Comment by Chesteer89** [comment]
Docs approved, merging to master. We'll merge the docs when the new release will be ready.

**Pull request merged**
